name: Deploy Spider Drop

on:
  push:
    branches:
    - secrets

jobs:
    
  build:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_PUBLIC}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_PRIVATE}}
      AWS_REGION: 'eu-west-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2.0.1
        with:
          secret-ids: |
            TawandaTest

      - name: Debug show secret value
        run: |
          echo "Secret Value: ${{ env.TAWANDATEST }}"
        
      - name: Create .env file and add DB_NAME
        run: |
          echo "DB_NAME=" > .env


      - name: Package artifact
        run: zip -r site.zip *

      - name: Upload artifact to S3
        run: aws s3 cp site.zip s3://${{ secrets.AWS_BUCKET_NAME }}/application-${{ github.run_id }}.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env: 
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_PUBLIC}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_PRIVATE}}
      AWS_REGION: 'eu-west-1'

    steps:
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name ${{ secrets.AWS_APP_NAME }} --version-label ${{ github.run_id }} --source-bundle S3Bucket="${{ secrets.AWS_BUCKET_NAME }}",S3Key="application-${{ github.run_id }}.zip"
          aws elasticbeanstalk update-environment --application-name ${{ secrets.AWS_APP_NAME }} --environment-name ${{ secrets.AWS_ENV_NAME }} --version-label ${{ github.run_id }}